[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = false

[tools]
ruby = "4.0.4"
node = "26"
python = "3.14.5"
starship = "latest"
atuin = "latest"
zoxide = "latest"
direnv = "latest"
lazydocker = "latest"
lazygit = "latest"
aube = "latest"
